n = int(input("Nhập vào số nguyên dương n: "))    
while n <= 0:  
    n = int(input("Vui lòng nhập số nguyên dương n: "))   
S1 = n * (n + 1) / 2  
S2 = (n + 1) * (n + 1) / 2  
S3 = n * (n + 1)  
print("S1 =", S1)  
print("S2 =", S2)  
print("S3 =", S3)  