mssv = input("Nhap ma so sinh vien: ")
ho_ten = input("Nhap ho va ten: ")
que_quan = input("Nhap que quan: ")
nam_sinh = input("Nhap nam sinh: ")
diem_tb = input("Nhap diem trung binh cac nam hoc: ")
print("\nThong tin sinh vien:")
print(f"Ma so sinh vien: {mssv}")
print(f"Ho va ten: {ho_ten}")
print(f"Que quan: {que_quan}")
print(f"Nam sinh: {nam_sinh}")
print(f"Diem trung binh: {diem_tb}")