ma_so_sv = input("Nhập mã số sinh viên: ")
ho_ten = input("Nhập họ và tên sinh viên: ")
que_quan = input("Nhập quê quán của sinh viên: ")
nam_sinh = input("Nhập năm sinh của sinh viên: ")
diem_tb = float(input("Nhập điểm trung bình các năm học: "))
print("\n--- Thông tin sinh viên ---")
print("Mã số sinh viên:", ma_so_sv)
print("Họ và tên:", ho_ten)
print("Quê quán:", que_quan)
print("Năm sinh:", nam_sinh)
print("Điểm trung bình:", diem_tb)
