x = float(input("Nhập tọa độ x: "))
y = float(input("Nhập tọa độ y: "))
z = float(input("Nhập tọa độ z: "))
doi_xung_oxy = (x, y, -z)   
doi_xung_oxz = (x, -y, z)   
doi_xung_oyz = (-x, y, z)  
print(f"Điểm đối xứng qua mặt phẳng Oxy: {doi_xung_oxy}")
print(f"Điểm đối xứng qua mặt phẳng Oxz: {doi_xung_oxz}")
print(f"Điểm đối xứng qua mặt phẳng Oyz: {doi_xung_oyz}")