msv=input("Moi nhap ma so sinh vien: ")
ho_ten=input("Moi nhap ho ten: ")
que_quan=input("Nhap que quan: ")
nam_sinh=input("Nhap nam sinh: ")
diem_tb=float(input("Nhap diem trung binh: "))
print("==========THONG TIN SINH VIEN========")
print("Ma so sinh vien: ",msv)
print("Ho va ten sinh vien: ",ho_ten)
print("Que quan:",que_quan)
print("Nam sinh: ",nam_sinh)
print("Diem trung binh cac nam hoc: %0.2f"%diem_tb)
