ma_so = input("Nhập mã số sinh viên:")
ten = input("Nhập tên sinh viên:")
que = input("Nhập quê quán sinh viên:")
nam_sinh = int(input("Nhập năm sinh của sinh viên:"))
diem = float(input("Nhập điểm trung bình các năm học của sinh viên:"))
print(ma_so)
print(ten)
print(que)
print(nam_sinh)
print(diem)
