ma_so = input("Nhap ma so sinh vien: ")
ho_ten = input("Nhap ho ten sinh vien: ")
que_quan = input("Nhap que quan: ")
nam_sinh = int(input("Nhap nam sinh: "))
diem_trung_binh = float(input("Nhap diem trung binh: "))

print("\n--- Thong tin sinh vien ---")
print(f"Ma so sinh vien: {ma_so}")
print(f"Ho ten sinh vien: {ho_ten}")
print(f"Que quan: {que_quan}")
print(f"Nam sinh: {nam_sinh}")
print(f"Diem trung binh: {diem_trung_binh}")