a = float(input("Nhập tọa độ a: "))
b = float(input("Nhập tọa độ b: "))
c = float(input("Nhập tọa độ c: "))
S_oxy = (a, b, -c)
S_oxz = (a, -b, c)
S_oyz = (-a, b, c)
print(f"Tọa độ đối xứng qua mặt phẳng Oxy: {S_oxy}")
print(f"Tọa độ đối xứng qua mặt phẳng Oxz: {S_oxz}")
print(f"Tọa độ đối xứng qua mặt phẳng Oyz: {S_oyz}")