ma_so = input("Nhập mã số sinh viên: ")
ho_ten = input("Nhập họ và tên sinh viên: ")
que_quan = input("Nhập quê quán: ")
nam_sinh = int(input("Nhập năm sinh: "))
diem_trung_binh = float(input("Nhập điểm trung bình các năm học: "))
print("\n--- Thông tin sinh viên ---")
print(f"Mã số sinh viên: {ma_so}")
print(f"Họ và tên: {ho_ten}")
print(f"Quê quán: {que_quan}")
print(f"Năm sinh: {nam_sinh}")
print(f"Điểm trung bình: {diem_trung_binh:.2f}") 
