msv = input("nhập mã sinh viên :") 
ht = input("nhập họ tên sinh viên :") 
qq = input("nhập quê quán sinh viên :") 
ns = input("nhập năm sinh sinh viên :") 
dtb = input("nhập điểm trung bình của sinh viên:") 
print("\n Thông tin sinh viên") 
print("mã số sinh viên là",msv) 
print("họ tên sinh viên là",ht) 
print("quê quán sinh viên ",qq) 
print("năm sinh: ",ns) 
print("điểm trung bình :",dtb) 