x = float(input("Nhập hoành độ x: ")) 
y = float(input("Nhập tung độ y: ")) 
z = float(input("Nhập cao độ z: ")) 
doi_xung_Oxy = (x, y, -z) 
doi_xung_Oxz = (x, -y, z) 
doi_xung_Oyz = (-x, y, z) 
print('Tọa độ đối xứng qua mặt phẳng Oxy: ', doi_xung_Oxy) 
print('Tọa độ đối xứng qua mặt phẳng Oxz: ', doi_xung_Oxz) 
print('Tọa độ đối xứng qua mặt phẳng Oyz: ', doi_xung_Oyz)